--DROP TABLE MMT_MAKE;

CREATE TABLE MMT_MAKE (
	ID int NOT NULL AUTO_INCREMENT,
	NAME varchar(12) NULL,
	PRIMARY KEY(ID)
);

--DROP TABLE MMT_MODEL;

CREATE TABLE MMT_MODEL (
	ID int NOT NULL AUTO_INCREMENT,
	MAKE_ID int NULL,
	CATEGORY varchar(25) NULL,
	NAME varchar(100) NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(MAKE_ID) REFERENCES MMT_MAKE(ID)
);

-- Add an index on the foreign key column to speed queries filtering by MAKE_ID
CREATE INDEX IDX_MMT_MODEL_MAKE_ID ON MMT_MODEL(MAKE_ID);

--DROP TABLE MMT_TYPE;

CREATE TABLE MMT_TYPE (
	ID int NOT NULL AUTO_INCREMENT,
	MODEL_ID int NULL,
	NAME varchar(100) NULL,
	BUILD_YEAR varchar(50) NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(MODEL_ID) REFERENCES MMT_MODEL(ID)
);

-- Add an index on the foreign key column to speed queries filtering by MODEL_ID
CREATE INDEX IDX_MMT_TYPE_MODEL_ID ON MMT_TYPE(MODEL_ID);
